id = "ballerina"
name = "Ballerina"
version = "0.1.1"
schema_version = 1
authors = ["oivanov"]
description = "Ballerina Swan Lake language support for Zed IDE"
repository = "https://gitlab.infotech.gov.ua/oleksii.ivanov/ballerina-extensions"

[grammars.ballerina]
repository = "https://gitlab.infotech.gov.ua/oleksii.ivanov/ballerina-extensions"
rev = "master"
path = "grammars/ballerina"

[language_servers.ballerina-language-server]
name = "Ballerina Language Server"
languages = ["Ballerina"]

[debug_adapters.ballerina]
name = "Ballerina Debugger"

