id = "ballerina"
name = "Ballerina"
version = "0.1.1"
schema_version = 1
authors = ["oivanov"]
description = "Ballerina Swan Lake language support for Zed IDE"
repository = "https://github.com/0875695/ballerina-extensions"

[grammars.ballerina]
repository = "https://github.com/0875695/ballerina-extensions.git"
rev = "aa953a7914b5ecee208543c29f669407b06dba43"

[language_servers.ballerina-language-server]
name = "Ballerina Language Server"
languages = ["Ballerina"]

[debug_adapters.ballerina]
name = "Ballerina Debugger"

